# Generated by Django 4.2.11 on 2024-04-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonedb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="gar_territory",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="operator",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="region",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="updatephonenumber",
            name="gar_territory",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="updatephonenumber",
            name="operator",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="updatephonenumber",
            name="region",
            field=models.CharField(max_length=1024),
        ),
    ]
